### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by burtontao** [motazalfarraj/Elastic-Impedance-Inversion-Using-Recurrent-Neural-Networks#4]
hi Alfarraj, i cannot download the dataset from url: https://www.dropbox.com/s/66u2hbbrvc15lyp/data.npy?raw=1, could u provide a new way to get the data? thx a lot!

**Comment by motazalfarraj** [comment]
Thanks for posting this issue. 
Here is the updated link: 
https://www.dropbox.com/s/qdbepx2jzz9jd9l/data.npy?raw=1
